version: "3.9"

services:
  db:
    image: postgres:15
    container_name: lastmile_db
    restart: always
    environment:
      POSTGRES_USER: lastmile
      POSTGRES_PASSWORD: lastmile@123
      POSTGRES_DB: lastmile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: lastmile_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: lastmile_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=postgres://lastmile:lastmile@db:5432/lastmile
      - REDIS_URL=redis://redis:6379

  frontend:
    build: ./frontend
    container_name: lastmile_frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:

