version: "3.9"

services:
  web:
    build: ./backend
    container_name: lastmile_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - media_data:/app/media
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: lastmile_db
    environment:
      - POSTGRES_DB=lastmile_db
      - POSTGRES_USER=lastmile_user
      - POSTGRES_PASSWORD=lastmile_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: lastmile_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  media_data:
