apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-loadbalancer
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-loadbalancer
  template:
    metadata:
      labels:
        app: nginx-loadbalancer
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          ports:
            - containerPort: 80
            - containerPort: 443
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
