apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
        - name: redis
          image: bitnami/redis:7.2
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_REPLICATION_MODE
              value: "master"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: REDIS_PASSWORD
