groups:
  - name: SSLAlerts
    rules:
      - alert: SSLCertificateExpiringSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate for {{ $labels.instance }} expires soon"
          description: "SSL certificate for {{ $labels.instance }} will expire in less than 10 days."
      - alert: SSLCertificateExpired
        expr: probe_ssl_earliest_cert_expiry - time() < 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "SSL certificate expired for {{ $labels.instance }}"
          description: "The SSL certificate for {{ $labels.instance }} has expired!"
